# Generated by Django 4.2.23 on 2025-07-03 00:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campanhas', '0008_alter_campanha_vigencia_fim'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoAcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('criado', 'Criado'), ('editado', 'Editado')], max_length=10)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('detalhe', models.TextField(blank=True)),
                ('campanha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campanhas.campanha')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
