# Generated by Django 4.2.23 on 2025-07-03 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campanhas', '0008_alter_campanha_vigencia_fim'),
        ('historico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicoacao',
            name='acao',
            field=models.CharField(choices=[('criado', 'Criado'), ('editado', 'Editado'), ('deletado', 'Deletado')], max_length=10),
        ),
        migrations.AlterField(
            model_name='historicoacao',
            name='campanha',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='campanhas.campanha'),
        ),
    ]
