# Generated by Django 4.2.23 on 2025-07-03 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campanhas', '0008_alter_campanha_vigencia_fim'),
        ('historico', '0002_alter_historicoacao_acao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicoacao',
            name='campanha',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campanhas.campanha'),
        ),
    ]
