# Generated by Django 4.2.23 on 2025-07-09 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historico', '0003_alter_historicoacao_campanha'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicoacao',
            name='campanha_nome',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
