# Generated by Django 4.2.23 on 2025-07-22 23:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campanhas', '0010_campanha_parametro_pagamento_and_more'),
        ('historico', '0005_historicoacao_vigencia_fim_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicoacao',
            name='acao',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='historicoacao',
            name='campanha',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historicos', to='campanhas.campanha'),
        ),
        migrations.AlterField(
            model_name='historicoacao',
            name='campanha_nome',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='historicoacao',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
