# Generated by Django 4.2.23 on 2025-07-30 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historico', '0006_alter_historicoacao_acao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicoacao',
            name='campanha_id_ref',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
