# Generated by Django 4.2.23 on 2025-06-25 21:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Banco Genérico', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Campanha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campanha', models.CharField(default=' ', max_length=200)),
                ('nomenclatura_wb', models.CharField(default=' ', max_length=200)),
                ('faixa_inicial', models.CharField(default=' ', max_length=200)),
                ('faixa_final', models.CharField(default=' ', max_length=200)),
                ('tipo_valor_meta', models.CharField(choices=[('R$', 'R$'), ('%', '%')], default='%', max_length=20)),
                ('tipo_valor', models.CharField(choices=[('R$', 'R$'), ('%', '%')], default='%', max_length=20)),
                ('tipo_valor_parametrizadowb', models.CharField(choices=[('R$', 'R$'), ('%', '%')], default=' ', max_length=20)),
                ('recebido', models.CharField(default=' ', max_length=200)),
                ('recebido_meta', models.CharField(default=' ', max_length=200)),
                ('parametrizado_wb', models.CharField(default=' ', max_length=200)),
                ('vigencia_inicio', models.DateField(default=django.utils.timezone.now)),
                ('vigencia_fim', models.DateField(default=django.utils.timezone.now)),
                ('periodicidade_repasses', models.CharField(default='Mensal', max_length=100)),
                ('previsao_pagamento', models.DateField(default=django.utils.timezone.now)),
                ('parametro_avaliacao', models.TextField(default='Sem parâmetros definidos.')),
                ('criterio_apuracao', models.TextField(default='Sem critérios definidos.')),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('possui_meta', models.BooleanField(default=False)),
                ('tem_garantido', models.BooleanField(default=False)),
                ('status_manual', models.CharField(choices=[('ATIVA', 'Ativa'), ('INATIVA', 'Inativa'), ('EM ANALISE', 'Em analise')], default='ATIVA', max_length=50)),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campanhas', to='campanhas.banco')),
            ],
        ),
    ]
