# Generated by Django 4.2.23 on 2025-06-26 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanhas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campanha',
            old_name='tipo_valor_parametrizadowb',
            new_name='tipo_valor_parametrizado_wb',
        ),
        migrations.RenameField(
            model_name='campanha',
            old_name='tipo_valor',
            new_name='tipo_valor_recebido',
        ),
        migrations.RenameField(
            model_name='campanha',
            old_name='tipo_valor_meta',
            new_name='tipo_valor_recebido_meta',
        ),
        migrations.AlterField(
            model_name='campanha',
            name='criterio_apuracao',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='campanha',
            name='parametro_avaliacao',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='campanha',
            name='periodicidade_repasses',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
