# Generated by Django 4.2.23 on 2025-06-26 20:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('campanhas', '0002_rename_tipo_valor_parametrizadowb_campanha_tipo_valor_parametrizado_wb_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campanha',
            name='recebido',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='campanha',
            name='tipo_valor_recebido',
            field=models.CharField(blank=True, choices=[('R$', 'R$'), ('%', '%')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='campanha',
            name='vigencia_fim',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
