# Generated by Django 4.2.23 on 2025-06-26 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanhas', '0003_alter_campanha_recebido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campanha',
            name='previsao_pagamento',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
