# Generated by Django 4.2.23 on 2025-06-26 21:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('campanhas', '0004_alter_campanha_previsao_pagamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campanha',
            name='faixa_final',
        ),
        migrations.RemoveField(
            model_name='campanha',
            name='faixa_inicial',
        ),
        migrations.RemoveField(
            model_name='campanha',
            name='recebido_meta',
        ),
        migrations.RemoveField(
            model_name='campanha',
            name='tipo_valor_recebido_meta',
        ),
        migrations.AlterField(
            model_name='campanha',
            name='parametrizado_wb',
            field=models.CharField(blank=True, default=' ', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='campanha',
            name='previsao_pagamento',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='campanha',
            name='recebido',
            field=models.CharField(blank=True, default=' ', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='campanha',
            name='tipo_valor_parametrizado_wb',
            field=models.CharField(blank=True, choices=[('R$', 'R$'), ('%', '%')], default=' ', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='campanha',
            name='tipo_valor_recebido',
            field=models.CharField(blank=True, choices=[('R$', 'R$'), ('%', '%')], default='%', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='campanha',
            name='vigencia_fim',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='FaixaMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faixa_inicial', models.DecimalField(decimal_places=2, max_digits=12)),
                ('faixa_final', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('tipo_valor', models.CharField(choices=[('R$', 'R$'), ('%', '%')], default='%', max_length=10)),
                ('valor_recebido', models.DecimalField(decimal_places=2, max_digits=12)),
                ('faixa_garantida', models.BooleanField(default=False)),
                ('campanha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faixas', to='campanhas.campanha')),
            ],
        ),
    ]
