# Generated by Django 4.2.23 on 2025-06-26 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanhas', '0005_remove_campanha_faixa_final_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campanha',
            name='previsao_pagamento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
