# Generated by Django 4.2.23 on 2025-06-27 00:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('campanhas', '0006_alter_campanha_previsao_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campanha',
            name='vigencia_fim',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
