# Generated by Django 4.2.23 on 2025-07-03 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanhas', '0007_alter_campanha_vigencia_fim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campanha',
            name='vigencia_fim',
            field=models.DateField(blank=True, null=True),
        ),
    ]
