# Generated by Django 4.2.23 on 2025-07-15 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanhas', '0008_alter_campanha_vigencia_fim'),
    ]

    operations = [
        migrations.AddField(
            model_name='campanha',
            name='inativada_automaticamente',
            field=models.BooleanField(default=False),
        ),
    ]
