# Generated by Django 4.2.23 on 2025-07-15 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanhas', '0009_campanha_inativada_automaticamente'),
    ]

    operations = [
        migrations.AddField(
            model_name='campanha',
            name='parametro_pagamento',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campanha',
            name='criterio_apuracao',
            field=models.TextField(blank=True, default=' ', null=True),
        ),
        migrations.AlterField(
            model_name='campanha',
            name='parametro_avaliacao',
            field=models.TextField(blank=True, default=' ', null=True),
        ),
        migrations.AlterField(
            model_name='campanha',
            name='periodicidade_repasses',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
