# Generated by Django 4.2.23 on 2025-07-23 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanhas', '0010_campanha_parametro_pagamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campanha',
            name='anexo_imagem',
            field=models.ImageField(blank=True, null=True, upload_to='campanha_anexos/'),
        ),
    ]
