# Generated by Django 4.2.23 on 2025-07-23 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanhas', '0011_campanha_anexo_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campanha',
            name='anexo_imagem',
        ),
        migrations.AddField(
            model_name='campanha',
            name='anexo',
            field=models.FileField(blank=True, null=True, upload_to='campanha_anexos/'),
        ),
    ]
